### ISSUE TITLE
[Feature request] Support custom name for font file

### ISSUE THREAD

**Issue by dmtrKovalenko** [RazrFalcon/fontdb#25]
My issue: Browsers allow you to provide a custom name for a font file and even do not expose the default provided by the file content font. So for something that mimics browser or rendering CSS it will be required to override the font family name when loading specific file. 

It would be great to have an API to provide the custom family name for the font face.

**Comment by RazrFalcon** [comment]
Yes, I thought about it just this weekend. Will add soon.

**Comment by yisibl** [comment]
Do you mean that the family name can be customized in the browser via  CSS `@font-face`?

e.g.

```css
@font-face {
  font-family: "myfont";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```
